// =============================================================================
// PayMaster Phase 7 — Deterministic Route Optimization Engine (domain types)
//
// The optimizer's job is to SELECT the best blockchain payment route from a set
// of *valid* candidate routes. Candidates are generated by Phase 6 (the planner
// — optionally with LLM-proposed strategies) and/or provided directly.
//
// Trust boundary (the optimizer NEVER invents a route):
//   Candidate Routes (from planner / API caller)
//     -> deterministic normalization of each factor to [0,1]
//     -> deterministic weighted scoring (LOWER IS BETTER)
//     -> deterministic ranking + recommendation reason
// The LLM is only allowed to *propose* candidate strategies (Phase 6). The
// final decision is made here, deterministically, by the mathematical model.
// =============================================================================

/**
 * Weights of the scoring model.
 *
 *   Score(r) = wg*Gas(r) + wt*Time(r) + ws*Steps(r) + wr*Risk(r)
 *
 * where wg + wt + ws + wr = 1 and each factor is normalized to [0,1].
 * Lower score is better.
 */
export interface RouteWeights {
  gas: number;
  time: number;
  steps: number;
  risk: number;
}

/**
 * Normalized factor breakdown for one route. Every value is in [0,1]
 * (min-max normalized across the candidate set) — 0 = best, 1 = worst.
 */
export interface RouteFactorBreakdown {
  gas: number;
  time: number;
  steps: number;
  risk: number;
}

/** Weighted contribution of each factor to the final score (wg*Gas(r) etc.). */
export interface RouteFactorContributions {
  gas: number;
  time: number;
  steps: number;
  risk: number;
}

/** Chain-preference soft-adjustment applied to the raw weighted score. */
export interface ChainPreference {
  /** Canonical preferred / requested chain id used for matching. */
  preferredChainId: number | null;
  /** Whether this route's terminal chain matches the preferred chain. */
  matches: boolean;
  /** Deterministic bonus subtracted from the raw score (0.02 when matching). */
  bonusApplied: number;
}

/** A candidate route input to the optimizer (provided by the caller / planner). */
export interface CandidateRoute {
  routeId: string;
  /** Short display label, e.g. "Ethereum direct transfer". */
  name?: string;
  description?: string;
  /** Ordered chain names/aliases, e.g. ["Ethereum", "Polygon"]. */
  chainSequence: string[];
  /** Ordered token symbols per hop, e.g. ["ETH", "USDC", "USDC"]. */
  tokenSequence: string[];
  /** Number of on-chain transactions the route executes. */
  transactionCount: number;
  /** Estimated total gas cost in USD. */
  estimatedGas: number;
  /** Estimated total execution time in seconds. */
  estimatedDuration: number;
  /** Route risk score 0-100 (higher = riskier). */
  riskScore: number;
  /** Asset the route spends out of the treasury (e.g. "ETH") for feasibility. */
  fundingAsset?: string | null;
  /** Upstream strategy family (native_direct / native_swap / ...) — display only. */
  strategy?: string | null;
  /** Where this candidate came from: llm-proposed strategy / deterministic / manual. */
  source?: "llm" | "deterministic" | "manual" | null;
}

/** The fully optimized route returned by the engine. */
export interface OptimizedRoute {
  routeId: string;
  name: string;
  description: string;
  /** Ordered chain names, e.g. ["Ethereum", "Polygon"]. */
  chainSequence: string[];
  /** Ordered token symbols, e.g. ["ETH", "USDC", "USDC"]. */
  tokenSequence: string[];
  /** Number of on-chain transactions. */
  transactionCount: number;
  /** Estimated total gas cost in USD. */
  estimatedGas: number;
  /** Estimated total duration in seconds. */
  estimatedDuration: number;
  /** Route risk score 0-100. */
  riskScore: number;
  /** Normalized weighted score in [0,1] — LOWER IS BETTER. */
  normalizedScore: number;
  /** Derived 0-100 index (higher = better) for display: (1 - score) * 100. */
  optimizationScore: number;
  /** Estimated USD saved versus the most expensive candidate (baseline). */
  estimatedSavings: number;
  /** Rank within the candidate set (1 = best). */
  rank: number;
  /** Deterministic reason the model recommends this route / ranked it here. */
  recommendationReason: string;
  isRecommended: boolean;
  /** True when the treasury cannot fund this route (retained with a penalty). */
  infeasible: boolean;
  /** Normalized factor breakdown (0 = best … 1 = worst). */
  factorBreakdown: RouteFactorBreakdown;
  /** Weighted contributions (wg*Gas(r) etc.). */
  contributions: RouteFactorContributions;
  /** Chain-preference soft bonus that was applied. */
  chainPreference: ChainPreference;
  /** Upstream strategy family (display only). */
  strategy: string | null;
  source: "llm" | "deterministic" | "manual" | null;
}

/** Treasury feasibility context used to gate candidate routes. */
export interface RouteTreasuryContext {
  /** Canonical preferred chain (name or alias), e.g. "ethereum". */
  preferredChain?: string | null;
  /** Requested delivery chain from the intent, e.g. "polygon". */
  targetChain?: string | null;
  /** Assets the treasury can actually spend. */
  availableAssets?: { symbol: string; balance?: string; usdValue?: number }[];
}

/** Optimizer configuration (weights + soft preference). */
export interface RouteOptimizerConfig {
  weights: RouteWeights;
  /** Explicit baseline gas for savings; defaults to the max candidate gas. */
  baselineGas?: number | null;
  /** Bonus subtracted from raw score when a route settles on the preferred chain. */
  preferenceBonus: number;
}

/** POST /api/route/optim request body (after Zod). */
export interface RouteOptimizerRequest {
  routes: CandidateRoute[];
  weights?: Partial<RouteWeights>;
  treasury?: RouteTreasuryContext;
  /** Explicit baseline gas in USD used for savings (defaults to max route gas). */
  baselineGas?: number | null;
  /** Optional source label surfaced in the result. */
  sourceLabel?: string | null;
}

/** Result of an optimization pass returned to callers / the API. */
export interface RouteOptimizerResult {
  /** Routes ranked best-first (lower normalizedScore first). */
  routes: OptimizedRoute[];
  recommendedRouteId: string | null;
  /** The weights that were actually used (user-supplied normalized to sum 1). */
  weights: RouteWeights;
  /** Baseline gas used for savings calculations. */
  baselineGas: number;
  /** Non-fatal notes (e.g. infeasible routes retained with a penalty). */
  warnings: string[];
  /** Determinstic — the engine never invents routes, only selects among them. */
  source: "optimizer";
}

export type RouteOptimizerErrorCode =
  | "EMPTY_ROUTES"
  | "NO_FEASIBLE_ROUTES"
  | "INVALID_ROUTE"
  | "INVALID_WEIGHTS"
  | "VALIDATION_FAILED";

/** Typed error thrown by the route optimizer service. */
export class RouteOptimizerError extends Error {
  constructor(
    public readonly code: RouteOptimizerErrorCode,
    message: string,
    public readonly details?: unknown
  ) {
    super(message);
    this.name = "RouteOptimizerError";
  }
}
