/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace IntentRouter {
  export type ExecutionStepStruct = {
    targetContract: AddressLike;
    callData: BytesLike;
    value: BigNumberish;
  };

  export type ExecutionStepStructOutput = [
    targetContract: string,
    callData: string,
    value: bigint
  ] & { targetContract: string; callData: string; value: bigint };
}

export interface IntentRouterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizedSolvers"
      | "executeIntentBatch"
      | "owner"
      | "setSolverAuthorization"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "IntentExecuted" | "SolverAuthorized"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizedSolvers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeIntentBatch",
    values: [BytesLike, AddressLike, IntentRouter.ExecutionStepStruct[]]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setSolverAuthorization",
    values: [AddressLike, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizedSolvers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeIntentBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setSolverAuthorization",
    data: BytesLike
  ): Result;
}

export namespace IntentExecutedEvent {
  export type InputTuple = [
    intentId: BytesLike,
    sender: AddressLike,
    recipient: AddressLike,
    totalSteps: BigNumberish
  ];
  export type OutputTuple = [
    intentId: string,
    sender: string,
    recipient: string,
    totalSteps: bigint
  ];
  export interface OutputObject {
    intentId: string;
    sender: string;
    recipient: string;
    totalSteps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SolverAuthorizedEvent {
  export type InputTuple = [solver: AddressLike, status: boolean];
  export type OutputTuple = [solver: string, status: boolean];
  export interface OutputObject {
    solver: string;
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IntentRouter extends BaseContract {
  connect(runner?: ContractRunner | null): IntentRouter;
  waitForDeployment(): Promise<this>;

  interface: IntentRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizedSolvers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  executeIntentBatch: TypedContractMethod<
    [
      intentId: BytesLike,
      recipient: AddressLike,
      steps: IntentRouter.ExecutionStepStruct[]
    ],
    [boolean],
    "payable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  setSolverAuthorization: TypedContractMethod<
    [solver: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizedSolvers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "executeIntentBatch"
  ): TypedContractMethod<
    [
      intentId: BytesLike,
      recipient: AddressLike,
      steps: IntentRouter.ExecutionStepStruct[]
    ],
    [boolean],
    "payable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setSolverAuthorization"
  ): TypedContractMethod<
    [solver: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "IntentExecuted"
  ): TypedContractEvent<
    IntentExecutedEvent.InputTuple,
    IntentExecutedEvent.OutputTuple,
    IntentExecutedEvent.OutputObject
  >;
  getEvent(
    key: "SolverAuthorized"
  ): TypedContractEvent<
    SolverAuthorizedEvent.InputTuple,
    SolverAuthorizedEvent.OutputTuple,
    SolverAuthorizedEvent.OutputObject
  >;

  filters: {
    "IntentExecuted(bytes32,address,address,uint256)": TypedContractEvent<
      IntentExecutedEvent.InputTuple,
      IntentExecutedEvent.OutputTuple,
      IntentExecutedEvent.OutputObject
    >;
    IntentExecuted: TypedContractEvent<
      IntentExecutedEvent.InputTuple,
      IntentExecutedEvent.OutputTuple,
      IntentExecutedEvent.OutputObject
    >;

    "SolverAuthorized(address,bool)": TypedContractEvent<
      SolverAuthorizedEvent.InputTuple,
      SolverAuthorizedEvent.OutputTuple,
      SolverAuthorizedEvent.OutputObject
    >;
    SolverAuthorized: TypedContractEvent<
      SolverAuthorizedEvent.InputTuple,
      SolverAuthorizedEvent.OutputTuple,
      SolverAuthorizedEvent.OutputObject
    >;
  };
}
