// =============================================================================
// GET /api/compliance/audit — compliance audit trail endpoint.
//
// Returns compliance audit events with filters:
//   ?date=2026-08-21        (created on this date)
//   ?customer=cust_techcorp
//   ?txn=TX-82931
//   ?risk=LOW|MEDIUM|HIGH|CRITICAL
//   ?decision=ALLOW|REVIEW|BLOCK
//   ?asset=USDC
//
// Live reads come from the `compliance_audit_log` table (service role). When
// Supabase is unconfigured or the table is missing, the endpoint returns a
// DETERMINISTIC demo dataset (isFallback:true) generated by the real
// compliance engines — so the Audit Log page always renders.
// =============================================================================

import { NextRequest, NextResponse } from "next/server";
import { getSupabaseAdmin, isSupabaseConfigured } from "@/lib/supabase/admin";
import { runCompliancePipeline, buildAuditEvent } from "@/lib/compliance/orchestrator";
import { COMPLETE_TRAVEL_RULE, INCOMPLETE_TRAVEL_RULE } from "@/lib/compliance/travelRule";
import type {
  ComplianceAuditEvent,
  ComplianceDecision,
  ComplianceRiskLevel,
  ScreeningVerdict,
  TravelRuleStatus,
} from "@/lib/compliance/types";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const TRUSTED = "0x71C7656EC7ab88b098defB751B7401B5f6d8976F";
const HIGH_RISK = "0x90F79bf6EB2c4f870365E785982E1f101E93b906";
const BLOCKED = "0x000000000000000000000000000000000000dEaD";

/** Deterministic demo audit dataset — every row driven by the REAL engines. */
function buildDemoAudit(): ComplianceAuditEvent[] {
  const rows: ComplianceAuditEvent[] = [];
  const base = {
    timestamp: Date.now(),
    dailyVolumeUsd: 0,
    counterpartyExposureUsd: 0,
    allocation: { USDC: 0.52, ETH: 0.23, BTC: 0.2 },
    stablecoinShare: 0.52,
  };

  const entries: {
    intent: string;
    recipient: string | null;
    recipientAddress: string;
    asset: string;
    amountUsd: number;
    network: string;
    txnReference: string;
    travelRulePayload: Parameters<typeof runCompliancePipeline>[0]["travelRulePayload"];
  }[] = [
    {
      intent: "Pay Acme Suppliers $5,000 USDC for invoice INV-1024.",
      recipient: "Acme Suppliers",
      recipientAddress: TRUSTED,
      asset: "USDC",
      amountUsd: 5000,
      network: "polygon",
      txnReference: "TX-82931",
      travelRulePayload: COMPLETE_TRAVEL_RULE,
    },
    {
      intent: "Pay contractor $50,000 USDC for project retainer.",
      recipient: "Freelance Contractor",
      recipientAddress: TRUSTED,
      asset: "USDC",
      amountUsd: 50000,
      network: "polygon",
      txnReference: "TX-82932",
      travelRulePayload: COMPLETE_TRAVEL_RULE,
    },
    {
      intent: "Pay new supplier $12,000 USDT.",
      recipient: "Unknown wallet",
      recipientAddress: HIGH_RISK,
      asset: "USDT",
      amountUsd: 12000,
      network: "ethereum",
      txnReference: "TX-82933",
      travelRulePayload: INCOMPLETE_TRAVEL_RULE,
    },
    {
      intent: "Pay blocked address $500.",
      recipient: "Blocked address",
      recipientAddress: BLOCKED,
      asset: "USDC",
      amountUsd: 500,
      network: "polygon",
      txnReference: "TX-82934",
      travelRulePayload: {},
    },
    {
      intent: "Pay Acme 500 XYZ tokens.",
      recipient: "Acme Suppliers",
      recipientAddress: TRUSTED,
      asset: "XYZ",
      amountUsd: 3000,
      network: "polygon",
      txnReference: "TX-82935",
      travelRulePayload: COMPLETE_TRAVEL_RULE,
    },
    {
      intent: "Top up treasury on Arbitrum $2,500 USDC.",
      recipient: "TechCorp Treasury",
      recipientAddress: "0x3C44CdD470368A0623A22D2c4022878d3F9905E5",
      asset: "USDC",
      amountUsd: 2500,
      network: "arbitrum",
      txnReference: "TX-82936",
      travelRulePayload: COMPLETE_TRAVEL_RULE,
    },
  ];

  entries.forEach((entry, i) => {
    const req: Parameters<typeof runCompliancePipeline>[0] = {
      intent: entry.intent,
      recipient: entry.recipient,
      recipientAddress: entry.recipientAddress,
      asset: entry.asset,
      amountUsd: entry.amountUsd,
      network: entry.network,
      customerId: "cust_techcorp",
      txnReference: entry.txnReference,
      travelRulePayload: entry.travelRulePayload,
      ...base,
    };
    rows.push(buildAuditEvent(runCompliancePipeline(req, { txnIndex: i }), req));
  });

  return rows;
}

/** Map a raw `compliance_audit_log` DB row (snake_case) to the camelCase event shape. */
function mapRowToEvent(row: Record<string, unknown>): ComplianceAuditEvent {
  const toNum = (v: unknown): number => {
    const n = typeof v === "number" ? v : Number(v);
    return Number.isFinite(n) ? n : 0;
  };
  const asArray = (v: unknown) => (Array.isArray(v) ? v : []);
  return {
    txnReference: String(row.txn_reference ?? ""),
    customerId: String(row.customer_id ?? ""),
    intent: String(row.intent ?? ""),
    recipient: row.recipient ? String(row.recipient) : "",
    recipientAddress: row.recipient_address ? String(row.recipient_address) : "",
    asset: String(row.asset ?? ""),
    amountUsd: toNum(row.amount_usd),
    screening: row.screening_verdict
      ? {
          verdict: String(row.screening_verdict) as ScreeningVerdict,
          riskScore: toNum(row.screening_risk_score),
        }
      : null,
    monitoringSignals: asArray(row.monitoring_signals) as ComplianceAuditEvent["monitoringSignals"],
    riskScore: toNum(row.risk_score),
    riskLevel: String(row.risk_level ?? "LOW") as ComplianceRiskLevel,
    policy: {
      decision: String(row.policy_decision ?? "REVIEW") as ComplianceDecision,
      violations: asArray(row.policy_violations) as string[],
    },
    travelRule: {
      status: String(row.travel_rule_status ?? "INCOMPLETE") as TravelRuleStatus,
      missing: asArray(row.travel_rule_missing) as ComplianceAuditEvent["travelRule"]["missing"],
    },
    decision: String(row.decision ?? "REVIEW") as ComplianceDecision,
    reviewer: row.reviewer ? String(row.reviewer) : null,
    executionStatus: String(row.execution_status ?? "PENDING_APPROVAL"),
    txHash: row.tx_hash ? String(row.tx_hash) : null,
    timestamp: String(row.timestamp ?? new Date().toISOString()),
    aiExplanation: row.ai_explanation ? String(row.ai_explanation) : null,
  };
}

export async function GET(req: NextRequest) {
  const sp = req.nextUrl.searchParams;
  const date = sp.get("date");
  const customer = sp.get("customer");
  const txn = sp.get("txn");
  const risk = sp.get("risk");
  const decision = sp.get("decision");
  const asset = sp.get("asset");

  const matches = (e: ComplianceAuditEvent) => {
    if (date && !e.timestamp.startsWith(date)) return false;
    if (customer && !e.customerId.toLowerCase().includes(customer.toLowerCase())) return false;
    if (txn && !e.txnReference.toLowerCase().includes(txn.toLowerCase())) return false;
    if (risk && e.riskLevel !== risk.toUpperCase()) return false;
    if (decision && e.decision !== decision.toUpperCase()) return false;
    if (asset && e.asset.toUpperCase() !== asset.toUpperCase()) return false;
    return true;
  };

  // ---- Live read (best-effort) ---------------------------------------------
  if (isSupabaseConfigured()) {
    try {
      const supabase = getSupabaseAdmin();
      let q = supabase.from("compliance_audit_log").select("*").order("timestamp", { ascending: false });
      if (date) q = q.gte("timestamp", `${date}T00:00:00`).lte("timestamp", `${date}T23:59:59`);
      if (customer) q = q.ilike("customer_id", `%${customer}%`);
      if (txn) q = q.ilike("txn_reference", `%${txn}%`);
      if (risk) q = q.eq("risk_level", risk.toUpperCase());
      if (decision) q = q.eq("decision", decision.toUpperCase());
      if (asset) q = q.eq("asset", asset.toUpperCase());

      const { data, error } = await q.limit(200);
      if (!error && Array.isArray(data)) {
        const events = (data as Record<string, unknown>[]).map(mapRowToEvent);
        return NextResponse.json({ success: true, events, isFallback: false });
      }
      if (error) console.error("[PayMaster-compliance] audit read error:", error.message);
    } catch (err) {
      console.error("[PayMaster-compliance] audit read failed:", err);
    }
  }

  // ---- Deterministic demo fallback ------------------------------------------
  const events = buildDemoAudit().filter(matches).sort((a, b) => b.timestamp.localeCompare(a.timestamp));
  return NextResponse.json({
    success: true,
    events,
    isFallback: true,
    fallbackReason: "Supabase unavailable — showing simulated compliance audit events.",
  });
}
