/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace SmartWallet {
  export type TransactionStruct = {
    target: AddressLike;
    value: BigNumberish;
    data: BytesLike;
  };

  export type TransactionStructOutput = [
    target: string,
    value: bigint,
    data: string
  ] & { target: string; value: bigint; data: string };
}

export interface SmartWalletInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptOwnership"
      | "approveToken"
      | "authorizedExecutors"
      | "batchExecute"
      | "executeTransaction"
      | "getBalance"
      | "getTokenBalance"
      | "nonce"
      | "owner"
      | "pendingOwner"
      | "setExecutorAuthorization"
      | "transferOwnership"
      | "transferToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BatchExecuted"
      | "ExecutorAuthorized"
      | "NativeTransfer"
      | "OwnershipTransferStarted"
      | "OwnershipTransferred"
      | "TokenApproval"
      | "TokenTransfer"
      | "TransactionExecuted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approveToken",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedExecutors",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "batchExecute",
    values: [SmartWallet.TransactionStruct[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeTransaction",
    values: [AddressLike, BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "nonce", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setExecutorAuthorization",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferToken",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedExecutors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchExecute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTokenBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nonce", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setExecutorAuthorization",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferToken",
    data: BytesLike
  ): Result;
}

export namespace BatchExecutedEvent {
  export type InputTuple = [
    batchId: BytesLike,
    transactionCount: BigNumberish,
    nonce: BigNumberish
  ];
  export type OutputTuple = [
    batchId: string,
    transactionCount: bigint,
    nonce: bigint
  ];
  export interface OutputObject {
    batchId: string;
    transactionCount: bigint;
    nonce: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutorAuthorizedEvent {
  export type InputTuple = [executor: AddressLike, status: boolean];
  export type OutputTuple = [executor: string, status: boolean];
  export interface OutputObject {
    executor: string;
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NativeTransferEvent {
  export type InputTuple = [
    to: AddressLike,
    value: BigNumberish,
    nonce: BigNumberish
  ];
  export type OutputTuple = [to: string, value: bigint, nonce: bigint];
  export interface OutputObject {
    to: string;
    value: bigint;
    nonce: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenApprovalEvent {
  export type InputTuple = [
    token: AddressLike,
    spender: AddressLike,
    amount: BigNumberish,
    caller: AddressLike
  ];
  export type OutputTuple = [
    token: string,
    spender: string,
    amount: bigint,
    caller: string
  ];
  export interface OutputObject {
    token: string;
    spender: string;
    amount: bigint;
    caller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenTransferEvent {
  export type InputTuple = [
    token: AddressLike,
    to: AddressLike,
    amount: BigNumberish,
    caller: AddressLike
  ];
  export type OutputTuple = [
    token: string,
    to: string,
    amount: bigint,
    caller: string
  ];
  export interface OutputObject {
    token: string;
    to: string;
    amount: bigint;
    caller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransactionExecutedEvent {
  export type InputTuple = [
    target: AddressLike,
    value: BigNumberish,
    data: BytesLike,
    nonce: BigNumberish
  ];
  export type OutputTuple = [
    target: string,
    value: bigint,
    data: string,
    nonce: bigint
  ];
  export interface OutputObject {
    target: string;
    value: bigint;
    data: string;
    nonce: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SmartWallet extends BaseContract {
  connect(runner?: ContractRunner | null): SmartWallet;
  waitForDeployment(): Promise<this>;

  interface: SmartWalletInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  approveToken: TypedContractMethod<
    [
      token: AddressLike,
      spender: AddressLike,
      amount: BigNumberish,
      _nonce: BigNumberish
    ],
    [boolean],
    "nonpayable"
  >;

  authorizedExecutors: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  batchExecute: TypedContractMethod<
    [txs: SmartWallet.TransactionStruct[], _nonce: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  executeTransaction: TypedContractMethod<
    [
      target: AddressLike,
      value: BigNumberish,
      data: BytesLike,
      _nonce: BigNumberish
    ],
    [boolean],
    "nonpayable"
  >;

  getBalance: TypedContractMethod<[], [bigint], "view">;

  getTokenBalance: TypedContractMethod<[token: AddressLike], [bigint], "view">;

  nonce: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  setExecutorAuthorization: TypedContractMethod<
    [executor: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  transferToken: TypedContractMethod<
    [
      token: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      _nonce: BigNumberish
    ],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "approveToken"
  ): TypedContractMethod<
    [
      token: AddressLike,
      spender: AddressLike,
      amount: BigNumberish,
      _nonce: BigNumberish
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "authorizedExecutors"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "batchExecute"
  ): TypedContractMethod<
    [txs: SmartWallet.TransactionStruct[], _nonce: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeTransaction"
  ): TypedContractMethod<
    [
      target: AddressLike,
      value: BigNumberish,
      data: BytesLike,
      _nonce: BigNumberish
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTokenBalance"
  ): TypedContractMethod<[token: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "nonce"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setExecutorAuthorization"
  ): TypedContractMethod<
    [executor: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferToken"
  ): TypedContractMethod<
    [
      token: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      _nonce: BigNumberish
    ],
    [boolean],
    "nonpayable"
  >;

  getEvent(
    key: "BatchExecuted"
  ): TypedContractEvent<
    BatchExecutedEvent.InputTuple,
    BatchExecutedEvent.OutputTuple,
    BatchExecutedEvent.OutputObject
  >;
  getEvent(
    key: "ExecutorAuthorized"
  ): TypedContractEvent<
    ExecutorAuthorizedEvent.InputTuple,
    ExecutorAuthorizedEvent.OutputTuple,
    ExecutorAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "NativeTransfer"
  ): TypedContractEvent<
    NativeTransferEvent.InputTuple,
    NativeTransferEvent.OutputTuple,
    NativeTransferEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TokenApproval"
  ): TypedContractEvent<
    TokenApprovalEvent.InputTuple,
    TokenApprovalEvent.OutputTuple,
    TokenApprovalEvent.OutputObject
  >;
  getEvent(
    key: "TokenTransfer"
  ): TypedContractEvent<
    TokenTransferEvent.InputTuple,
    TokenTransferEvent.OutputTuple,
    TokenTransferEvent.OutputObject
  >;
  getEvent(
    key: "TransactionExecuted"
  ): TypedContractEvent<
    TransactionExecutedEvent.InputTuple,
    TransactionExecutedEvent.OutputTuple,
    TransactionExecutedEvent.OutputObject
  >;

  filters: {
    "BatchExecuted(bytes32,uint256,uint256)": TypedContractEvent<
      BatchExecutedEvent.InputTuple,
      BatchExecutedEvent.OutputTuple,
      BatchExecutedEvent.OutputObject
    >;
    BatchExecuted: TypedContractEvent<
      BatchExecutedEvent.InputTuple,
      BatchExecutedEvent.OutputTuple,
      BatchExecutedEvent.OutputObject
    >;

    "ExecutorAuthorized(address,bool)": TypedContractEvent<
      ExecutorAuthorizedEvent.InputTuple,
      ExecutorAuthorizedEvent.OutputTuple,
      ExecutorAuthorizedEvent.OutputObject
    >;
    ExecutorAuthorized: TypedContractEvent<
      ExecutorAuthorizedEvent.InputTuple,
      ExecutorAuthorizedEvent.OutputTuple,
      ExecutorAuthorizedEvent.OutputObject
    >;

    "NativeTransfer(address,uint256,uint256)": TypedContractEvent<
      NativeTransferEvent.InputTuple,
      NativeTransferEvent.OutputTuple,
      NativeTransferEvent.OutputObject
    >;
    NativeTransfer: TypedContractEvent<
      NativeTransferEvent.InputTuple,
      NativeTransferEvent.OutputTuple,
      NativeTransferEvent.OutputObject
    >;

    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TokenApproval(address,address,uint256,address)": TypedContractEvent<
      TokenApprovalEvent.InputTuple,
      TokenApprovalEvent.OutputTuple,
      TokenApprovalEvent.OutputObject
    >;
    TokenApproval: TypedContractEvent<
      TokenApprovalEvent.InputTuple,
      TokenApprovalEvent.OutputTuple,
      TokenApprovalEvent.OutputObject
    >;

    "TokenTransfer(address,address,uint256,address)": TypedContractEvent<
      TokenTransferEvent.InputTuple,
      TokenTransferEvent.OutputTuple,
      TokenTransferEvent.OutputObject
    >;
    TokenTransfer: TypedContractEvent<
      TokenTransferEvent.InputTuple,
      TokenTransferEvent.OutputTuple,
      TokenTransferEvent.OutputObject
    >;

    "TransactionExecuted(address,uint256,bytes,uint256)": TypedContractEvent<
      TransactionExecutedEvent.InputTuple,
      TransactionExecutedEvent.OutputTuple,
      TransactionExecutedEvent.OutputObject
    >;
    TransactionExecuted: TypedContractEvent<
      TransactionExecutedEvent.InputTuple,
      TransactionExecutedEvent.OutputTuple,
      TransactionExecutedEvent.OutputObject
    >;
  };
}
